AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Lambda application that calls the Lambda API.
Resources:
  api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: api
      TracingEnabled: true
      OpenApiVersion: 3.0.2
  function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: ./function/event.handler
      Runtime: nodejs18.x
      CodeUri: s3://lambda-artifacts-6bb56f0982bf22fc/383c3d80792e336cdf0789b56c5fcc3b
      Description: Call the AWS Lambda API
      Timeout: 10
      Policies:
      - AWSLambdaBasicExecutionRole
      - AWSLambda_ReadOnlyAccess
      - AWSXrayWriteOnlyAccess
      Tracing: Active
      Events:
        getEndpoint:
          Type: Api
          Properties:
            RestApiId:
              Ref: api
            Path: /event
            Method: GET
        postEndpoint:
          Type: Api
          Properties:
            RestApiId:
              Ref: api
            Path: /event
            Method: POST
  userFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: ./function/user.handler
      Runtime: nodejs18.x
      CodeUri: s3://lambda-artifacts-6bb56f0982bf22fc/383c3d80792e336cdf0789b56c5fcc3b
      Description: Call the AWS Lambda API
      Timeout: 10
      Policies:
      - AWSLambdaBasicExecutionRole
      - AWSLambda_ReadOnlyAccess
      - AWSXrayWriteOnlyAccess
      Tracing: Active
      Events:
        getEndpoint:
          Type: Api
          Properties:
            RestApiId:
              Ref: api
            Path: /user
            Method: GET
        putEndpoint:
          Type: Api
          Properties:
            RestApiId:
              Ref: api
            Path: /user
            Method: PUT
